// Code generated by goplus from reload.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Go+ reload and immutable snapshot semantics.
package viper

import (
	"context"
	"errors"
	"sync"
)

var ErrReloadStreamClosed = errors.New("viper: reload stream closed")

// ReloadEvent is one completed reload attempt. A successful event owns an
// immutable snapshot; a failed event owns its error and leaves prior snapshots
// untouched. Version increases for every attempt, including failures.
type ReloadEvent struct {
	Version  uint64
	Snapshot Snapshot
	Err      error
}

// Loader performs the effectful portion of a reload. Parsing files, consulting
// remote systems, and rebuilding a registry happen here rather than inside
// Snapshot reads.
type Loader func(context.Context) (*Viper, error)

// ReloadStream serializes reload attempts and publishes their exhaustive
// success/failure events. It never mutates a previously published Snapshot.
type ReloadStream struct {
	mu     sync.Mutex
	next   uint64
	closed bool
	events chan ReloadEvent
}

func NewReloadStream(buffer int) *ReloadStream {
	if buffer < 0 {
		panic("viper: negative reload buffer")
	}
	return &ReloadStream{events: make(chan ReloadEvent, buffer)}
}

func (stream *ReloadStream) Events() <-chan ReloadEvent { return stream.events }

func (stream *ReloadStream) Reload(ctx context.Context, load Loader) (ReloadEvent, error) {
	if load == nil {
		return ReloadEvent{}, errors.New("viper: nil reload loader")
	}
	stream.mu.Lock()
	defer stream.mu.Unlock()
	if stream.closed {
		return ReloadEvent{}, ErrReloadStreamClosed
	}
	stream.next++
	event := ReloadEvent{Version: stream.next}
	registry, err := load(ctx)
	if err != nil {
		event.Err = err
	} else if registry == nil {
		event.Err = errors.New("viper: reload loader returned nil registry")
	} else {
		event.Snapshot = registry.Snapshot()
	}
	select {
	case stream.events <- event:
		return event, nil
	case <-ctx.Done():
		return ReloadEvent{}, ctx.Err()
	}
}

func (stream *ReloadStream) Close() error {
	stream.mu.Lock()
	defer stream.mu.Unlock()
	if stream.closed {
		return ErrReloadStreamClosed
	}
	stream.closed = true
	close(stream.events)
	return nil
}
